
// This file has been generated by the GUI designer. Do not modify.
namespace ConnectFourGUI
{
	public partial class PlayerEntryWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ConnectFourGUI.PlayerEntryWindow
			this.Name = "ConnectFourGUI.PlayerEntryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Player Entry");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 396;
			this.DefaultHeight = 372;
			this.Show();
		}
	}
}
