
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Alignment alignment4;

	private global::Gtk.Label connect4sign;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Button newGameBtn;

	private global::Gtk.Button loadGameBtn;

	private global::Gtk.Button settingsBtn;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Button quitBtn;

	private global::Gtk.Alignment alignment5;

	private global::Gtk.Alignment alignment12;

	private global::Gtk.Alignment alignment9;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Main Menu");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment4.HeightRequest = 80;
		this.alignment4.Name = "alignment4";
		this.vbox3.Add(this.alignment4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment4]));
		w1.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.connect4sign = new global::Gtk.Label();
		this.connect4sign.WidthRequest = 200;
		this.connect4sign.Name = "connect4sign";
		this.connect4sign.LabelProp = global::Mono.Unix.Catalog.GetString("Connect 4 Game");
		this.vbox3.Add(this.connect4sign);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.connect4sign]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.vbox3.Add(this.alignment1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment1]));
		w3.Position = 2;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w4.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.newGameBtn = new global::Gtk.Button();
		this.newGameBtn.CanFocus = true;
		this.newGameBtn.Name = "newGameBtn";
		this.newGameBtn.UseUnderline = true;
		this.newGameBtn.Label = global::Mono.Unix.Catalog.GetString("New Game");
		this.vbox5.Add(this.newGameBtn);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.newGameBtn]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.loadGameBtn = new global::Gtk.Button();
		this.loadGameBtn.CanFocus = true;
		this.loadGameBtn.Name = "loadGameBtn";
		this.loadGameBtn.UseUnderline = true;
		this.loadGameBtn.Label = global::Mono.Unix.Catalog.GetString("Load Game");
		this.vbox5.Add(this.loadGameBtn);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.loadGameBtn]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.settingsBtn = new global::Gtk.Button();
		this.settingsBtn.CanFocus = true;
		this.settingsBtn.Name = "settingsBtn";
		this.settingsBtn.UseUnderline = true;
		this.settingsBtn.Label = global::Mono.Unix.Catalog.GetString("Settings");
		this.vbox5.Add(this.settingsBtn);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.settingsBtn]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox5]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.HeightRequest = 150;
		this.alignment3.Name = "alignment3";
		this.vbox7.Add(this.alignment3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment3]));
		w9.Position = 0;
		// Container child vbox7.Gtk.Box+BoxChild
		this.quitBtn = new global::Gtk.Button();
		this.quitBtn.CanFocus = true;
		this.quitBtn.Name = "quitBtn";
		this.quitBtn.UseUnderline = true;
		this.quitBtn.Label = global::Mono.Unix.Catalog.GetString("Quit");
		this.vbox7.Add(this.quitBtn);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.quitBtn]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.vbox7.Add(this.alignment5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment5]));
		w11.Position = 2;
		this.vbox1.Add(this.vbox7);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox7]));
		w12.Position = 2;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment12.WidthRequest = 300;
		this.alignment12.Name = "alignment12";
		this.hbox1.Add(this.alignment12);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment12]));
		w14.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment9.WidthRequest = 150;
		this.alignment9.Name = "alignment9";
		this.hbox1.Add(this.alignment9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment9]));
		w15.Position = 2;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 696;
		this.DefaultHeight = 486;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.newGameBtn.Clicked += new global::System.EventHandler(this.OnNewGameBtnClicked);
		this.loadGameBtn.Clicked += new global::System.EventHandler(this.OnLoadGameBtnClicked);
		this.settingsBtn.Clicked += new global::System.EventHandler(this.OnSettingsBtnClicked);
		this.quitBtn.Clicked += new global::System.EventHandler(this.OnQuitBtnClicked);
	}
}
